language: node_js
node_js:
  - "node"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - release-linux-ia32
    - release
    - build-cache
    - build-desktop
install:
  - sudo apt-get install fakeroot
  - npm install
script:
  - npm run release
  - git clean -f
  - git remote set-url origin "$GIT_SELF_REPO_URL"
  - node node_modules/release-it/bin/release-it.js -n --verbose --debug --no-npm.publish